name: croupier
dependencies:
  v23discovery: ">=0.0.0 <0.1.0"
  syncbase: ">=0.0.0 <0.1.0"
  flutter:
    path: ../../../../../flutter/packages/flutter
  sky_tools:
    path: ../../../../../flutter/packages/flutter_tools
  test: any

dependency_overrides:
  v23discovery:
    path: ../../mojo/discovery