name: croupier
dependencies:
  discovery: ">=0.0.0 <0.1.0"
  syncbase: ">=0.0.0 <0.1.0"
  flutter: "0.0.14"
  sky_tools: any
  test: any

dependency_overrides:
  discovery:
    path: ../../mojo/discovery